### PR TITLE
Reduce Inclusions / Redirections

### PR DESCRIPTION
**Pull request by thecapacity**
Having team-list (which is largely empty already) include teammates.html it didn’t make sense - this should be simpler.

### CODE REVIEW

**Comment by wslack** [comment]
🤔  I get that, but isn't it simpler to make the team list a component that can be moved around?

**Comment by thecapacity** [comment]
I don't understand how it's not still a component? FWIW though, no I don't think I agree cause I don't understand and as it stands currently there's basically content in two different places one of which doesn't actually have much content or value.

take it or leave it, just trying to surface things I'm struggling w/

**Comment by wslack** [comment]
Our list of layouts is a starting place, but you can't "include" a thing from a layout in another page. If someone wants to make an alternative layout with the team list, that's much easier to include as is.

In other words, "layouts" (to me) represent the types of pages you might want. Components represent the "stuff" you might put in those pages, and we should try to use components whenever possible.

**Comment by wslack** [comment]
In fact, maybe a template should have multiple layouts that use the same component so people can choose from the options via elimination instead of trying to be a "complete" website with one of everything.

**Comment by thecapacity** [comment]
I think that's a good distinction and probably highlights the difference in opinion. to me a "team page" is just that - and I can't imagine a situation where I'd have multiple views of "team" - but certainly if you can than `_include` makes more sense. 

My Q then would be why can't `team.md` (assuming type page) just directly include the `_includes/teammates.html` vs. having a team-specific layout that only includes the `teammates.html` component?

**Comment by wslack** [comment]
That's a good question. I assume to make it easier to customize but that change makes sense.

**Pull request closed without merging**
